export type CountryCode = "mx" | "co" | "ar" | "es" | "cl" | "pe" | "ec" | "uy" | "cr" | "ve" | "us" | "pa" | "do" | "hn" | "sv" | "gt" | "py" | "bo" | "ni" | "pr" | "gq"

export interface CountryConfig {
  code: CountryCode
  name: string
  demonym: string
  childTerm: string // "niños" vs "chicos" vs "chavales"
  currency: string
  currencySymbol: string
  priceUSD: number
  priceLocal: number
  priceDisplay: string
  reservationPrice: number
  reservationPriceDisplay: string
  whatsapp: string
  timezone: string
  mainCity: string
  otherCities: string[]
  locale: string
  hreflang: string
  tone: string
  keywords: string[]
  longTailKeywords: string[]
  paymentMethods: string[]
  flag: string
  metaTitle: string
  metaDescription: string
  heroSubtext: string
  faqPaymentAnswer: string
}

export const countriesConfig: Record<CountryCode, CountryConfig> = {
  cl: {
    code: "cl",
    name: "Chile",
    demonym: "chilenos",
    childTerm: "niños",
    currency: "CLP",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 250000,
    priceDisplay: "$250.000 CLP",
    reservationPrice: 25000,
    reservationPriceDisplay: "$25.000 CLP",
    whatsapp: "+56964754219",
    timezone: "America/Santiago",
    mainCity: "Santiago",
    otherCities: ["Viña del Mar", "Valparaíso", "Concepción", "La Serena"],
    locale: "es_CL",
    hreflang: "es-CL",
    tone: "Prepáralos para el futuro digital",
    keywords: ["cursos de IA para niños santiago", "clases inteligencia artificial infantil chile"],
    longTailKeywords: ["donde estudiar ia niños en chile"],
    paymentMethods: ["Webpay", "Mercado Pago", "PayPal", "Transferencia"],
    flag: "🇨🇱",
    metaTitle: "Curso de IA para Niños en Chile | Online y Certificado | InnovaKids",
    metaDescription: "🇨🇱 Curso #1 de IA para niños en Chile (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Santiago, Viña del Mar, Concepción y todo Chile ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito directamente, con Mercado Pago, PayPal o transferencia bancaria. La reserva es de $27 USD (aprox. $25.000 CLP). Solo pagas el resto después de las 2 primeras clases."
  },
  mx: {
    code: "mx",
    name: "México",
    demonym: "mexicanos",
    childTerm: "niños",
    currency: "MXN",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 5400,
    priceDisplay: "$5,400 MXN",
    reservationPrice: 540,
    reservationPriceDisplay: "$540 MXN",
    whatsapp: "+56964754219",
    timezone: "America/Mexico_City",
    mainCity: "CDMX",
    otherCities: ["Guadalajara", "Monterrey", "Puebla", "Tijuana"],
    locale: "es_MX",
    hreflang: "es-MX",
    tone: "Dale una ventaja competitiva a tu hijo",
    keywords: ["cursos de inteligencia artificial para niños mx", "clases de IA para niños cdmx"],
    longTailKeywords: ["donde aprenden IA mis hijos en méxico"],
    paymentMethods: ["OXXO", "Mercado Pago", "PayPal", "Tarjeta de crédito"],
    flag: "🇲🇽",
    metaTitle: "Curso de IA para Niños en México | Online y Certificado | InnovaKids",
    metaDescription: "🇲🇽 Curso #1 de IA para niños en México (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Ciudad de México, Guadalajara, Monterrey y todo México ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito directamente, con Mercado Pago o PayPal. La reserva es de $27 USD (aprox. $540 MXN). Solo pagas el resto después de las 2 primeras clases."
  },
  co: {
    code: "co",
    name: "Colombia",
    demonym: "colombianos",
    childTerm: "niños",
    currency: "COP",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 1120000,
    priceDisplay: "$1.120.000 COP",
    reservationPrice: 113000,
    reservationPriceDisplay: "$113.000 COP",
    whatsapp: "+56964754219",
    timezone: "America/Bogota",
    mainCity: "Bogotá",
    otherCities: ["Medellín", "Cali", "Barranquilla", "Cartagena"],
    locale: "es_CO",
    hreflang: "es-CO",
    tone: "Impulsa su creatividad y espíritu innovador",
    keywords: ["cursos de inteligencia artificial para niños bogotá", "clases de IA para niños colombia"],
    longTailKeywords: ["donde estudiar ia niños en colombia"],
    paymentMethods: ["PSE", "Nequi", "Daviplata", "Mercado Pago"],
    flag: "🇨🇴",
    metaTitle: "Curso de IA para Niños en Colombia | Online y Certificado | InnovaKids",
    metaDescription: "🇨🇴 Curso #1 de IA para niños en Colombia (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Bogotá, Medellín, Cali, Barranquilla y toda Colombia ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito (Visa, Mastercard, American Express), con Mercado Pago o PayPal. La reserva es de $27 USD (aprox. $113.000 COP). Solo pagas el resto después de las 2 primeras clases."
  },
  ar: {
    code: "ar",
    name: "Argentina",
    demonym: "argentinos",
    childTerm: "chicos",
    currency: "ARS",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 285000,
    priceDisplay: "$285.000 ARS (Aprox)",
    reservationPrice: 29000,
    reservationPriceDisplay: "$29.000 ARS (Aprox)",
    whatsapp: "+56964754219",
    timezone: "America/Argentina/Buenos_Aires",
    mainCity: "Buenos Aires",
    otherCities: ["Córdoba", "Rosario", "Mendoza", "La Plata"],
    locale: "es_AR",
    hreflang: "es-AR",
    tone: "Potencia su pensamiento crítico creando tecnología",
    keywords: ["cursos de inteligencia artificial para chicos argentina", "talleres de IA para niños"],
    longTailKeywords: ["donde aprenden ia los chicos en argentina"],
    paymentMethods: ["Mercado Pago", "Transferencia", "PayPal"],
    flag: "🇦🇷",
    metaTitle: "Curso de IA para Chicos en Argentina | Online y Certificado | InnovaKids",
    metaDescription: "🇦🇷 Curso #1 de IA para chicos en Argentina (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Buenos Aires, Córdoba, Rosario y toda Argentina ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito internacional (el cobro es en USD), con Mercado Pago o PayPal. La reserva es de $27 USD. Solo pagas el resto después de las 2 primeras clases."
  },
  pe: {
    code: "pe",
    name: "Perú",
    demonym: "peruanos",
    childTerm: "niños",
    currency: "PEN",
    currencySymbol: "S/",
    priceUSD: 267,
    priceLocal: 1000,
    priceDisplay: "S/ 1.000 PEN",
    reservationPrice: 100,
    reservationPriceDisplay: "S/ 100 PEN",
    whatsapp: "+56964754219",
    timezone: "America/Lima",
    mainCity: "Lima",
    otherCities: ["Arequipa", "Trujillo", "Cusco", "Piura"],
    locale: "es_PE",
    hreflang: "es-PE",
    tone: "Educación tecnológica de clase mundial",
    keywords: ["cursos de inteligencia artificial para niños lima", "clases de IA para niños perú"],
    longTailKeywords: ["donde estudiar ia niños en perú"],
    paymentMethods: ["Yape", "Plin", "Mercado Pago", "PayPal"],
    flag: "🇵🇪",
    metaTitle: "Curso de IA para Niños en Perú | Online y Certificado | InnovaKids",
    metaDescription: "🇵🇪 Curso #1 de IA para niños en Perú (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Lima, Arequipa, Trujillo y todo Perú ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito (Visa, Mastercard), con Mercado Pago o PayPal. La reserva es de $27 USD (aprox. S/ 100). Solo pagas el resto después de las 2 primeras clases."
  },
  es: {
    code: "es",
    name: "España",
    demonym: "españoles",
    childTerm: "niños",
    currency: "EUR",
    currencySymbol: "€",
    priceUSD: 267,
    priceLocal: 245,
    priceDisplay: "245€",
    reservationPrice: 25,
    reservationPriceDisplay: "25€",
    whatsapp: "+56964754219",
    timezone: "Europe/Madrid",
    mainCity: "Madrid",
    otherCities: ["Barcelona", "Valencia", "Sevilla", "Bilbao"],
    locale: "es_ES",
    hreflang: "es-ES",
    tone: "Formación tecnológica de alta calidad",
    keywords: ["cursos de inteligencia artificial para niños españa"],
    longTailKeywords: ["mejores cursos de ia para niños madrid"],
    paymentMethods: ["Tarjeta", "Bizum", "PayPal"],
    flag: "🇪🇸",
    metaTitle: "Curso de IA para Niños en España | Online y Certificado | InnovaKids",
    metaDescription: "🇪🇸 Curso #1 de IA para niños en España (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Madrid, Barcelona, Valencia, Sevilla y toda España ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito directamente, o con PayPal. La reserva es de solo 25€. Tu hijo prueba las 2 primeras clases y solo si te convence pagas el resto (220€)."
  },
  ec: {
    code: "ec",
    name: "Ecuador",
    demonym: "ecuatorianos",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Guayaquil",
    mainCity: "Quito",
    otherCities: ["Guayaquil", "Cuenca", "Ambato"],
    locale: "es_EC",
    hreflang: "es-EC",
    tone: "Innovación y tecnología al alcance de tus hijos",
    keywords: ["cursos de ia para niños ecuador"],
    longTailKeywords: ["clases de computación para niños guayaquil"],
    paymentMethods: ["Tarjeta", "PayPal", "Mercado Pago"],
    flag: "🇪🇨",
    metaTitle: "Curso de IA para Niños en Ecuador | Online y Certificado | InnovaKids",
    metaDescription: "🇪🇨 Curso #1 de IA para niños en Ecuador (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Quito, Guayaquil, Cuenca y todo Ecuador ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito directamente, PayPal o Mercado Pago. La reserva es de $27 USD."
  },
  uy: {
    code: "uy",
    name: "Uruguay",
    demonym: "uruguayos",
    childTerm: "chiquilines",
    currency: "UYU",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 11500,
    priceDisplay: "$11.500 UYU",
    reservationPrice: 1160,
    reservationPriceDisplay: "$1.160 UYU",
    whatsapp: "+56964754219",
    timezone: "America/Montevideo",
    mainCity: "Montevideo",
    otherCities: ["Punta del Este", "Salto", "Ciudad de la Costa"],
    locale: "es_UY",
    hreflang: "es-UY",
    tone: "Educación de calidad para el futuro",
    keywords: ["cursos de programación para niños uruguay"],
    longTailKeywords: ["escuela de programación para niños montevideo"],
    paymentMethods: ["Tarjeta", "Mercado Pago", "PayPal"],
    flag: "🇺🇾",
    metaTitle: "Curso de IA para Niños en Uruguay | Online y Certificado | InnovaKids",
    metaDescription: "🇺🇾 Curso #1 de IA para niños en Uruguay (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Montevideo, Punta del Este y todo Uruguay ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito, Mercado Pago o PayPal. La reserva es de $27 USD (aprox $1.160 UYU)."
  },
  cr: {
    code: "cr",
    name: "Costa Rica",
    demonym: "ticos",
    childTerm: "niños",
    currency: "CRC",
    currencySymbol: "₡",
    priceUSD: 267,
    priceLocal: 137000,
    priceDisplay: "₡137.000 CRC",
    reservationPrice: 14000,
    reservationPriceDisplay: "₡14.000 CRC",
    whatsapp: "+56964754219",
    timezone: "America/Costa_Rica",
    mainCity: "San José",
    otherCities: ["Heredia", "Alajuela", "Cartago"],
    locale: "es_CR",
    hreflang: "es-CR",
    tone: "Líderes en educación tecnológica",
    keywords: ["cursos de ia costa rica niños"],
    longTailKeywords: ["clases de robotica y programacion para niños costa rica"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇨🇷",
    metaTitle: "Curso de IA para Niños en Costa Rica | Online y Certificado | InnovaKids",
    metaDescription: "🇨🇷 Curso #1 de IA para niños en Costa Rica (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en San José, Heredia, Alajuela y toda Costa Rica ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tu tarjeta de crédito o débito o PayPal. La reserva es de $27 USD (aprox ₡14.000 CRC)."
  },
  ve: {
    code: "ve",
    name: "Venezuela",
    demonym: "venezolanos",
    childTerm: "chamos",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Caracas",
    mainCity: "Caracas",
    otherCities: ["Maracaibo", "Valencia", "Barquisimeto"],
    locale: "es_VE",
    hreflang: "es-VE",
    tone: "Tecnología global y oportunidades de futuro",
    keywords: ["cursos de ia en venezuela para niños"],
    longTailKeywords: ["clases de programacion para niños caracas"],
    paymentMethods: ["Zelle", "Binance", "PayPal"],
    flag: "🇻🇪",
    metaTitle: "Curso de IA para Niños en Venezuela | Online y Certificado | InnovaKids",
    metaDescription: "🇻🇪 Curso #1 de IA para niños en Venezuela (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Caracas, Maracaibo, Valencia y toda Venezuela ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Ofrecemos facilidades para Venezuela: Zelle, PayPal, Binance USDT o tarjetas internacionales. La reserva es de $27 USD."
  },
  us: {
    code: "us",
    name: "Estados Unidos",
    demonym: "latinos",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/New_York",
    mainCity: "Miami",
    otherCities: ["Los Angeles", "Houston", "New York", "Chicago"],
    locale: "es_US",
    hreflang: "es-US",
    tone: "Vibe Coding: La ventaja bilingüe y tecnológica",
    keywords: ["clases de ia para niños latinos usa", "cursos programación niños español usa"],
    longTailKeywords: ["coding for kids in spanish usa"],
    paymentMethods: ["Credit Card", "PayPal", "Zelle"],
    flag: "🇺🇸",
    metaTitle: "Clases de IA para Niños Latinos en USA | Online y en Español | InnovaKids",
    metaDescription: "🇺🇸 Curso #1 de programación e IA para niños latinos en USA (8-17 años). Clases 100% en español. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias latinas en Miami, California, Texas y todo USA ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con cualquier tarjeta de crédito o débito de USA, Zelle o PayPal. La reserva es de $27 USD."
  },
  pa: {
    code: "pa",
    name: "Panamá",
    demonym: "panameños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Panama",
    mainCity: "Ciudad de Panamá",
    otherCities: ["Colón", "David", "Santiago"],
    locale: "es_PA",
    hreflang: "es-PA",
    tone: "Innovación desde el Hub de las Américas",
    keywords: ["cursos de ia para niños panama", "clases de robotica panama"],
    longTailKeywords: ["escuela de programacion para niños en panama"],
    paymentMethods: ["Tarjeta", "PayPal", "Yappy"],
    flag: "🇵🇦",
    metaTitle: "Curso de IA para Niños en Panamá | Online y Certificado | InnovaKids",
    metaDescription: "🇵🇦 Curso #1 de IA para niños en Panamá (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Ciudad de Panamá, Colón y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito, PayPal o Yappy. La reserva es de $27 USD."
  },
  do: {
    code: "do",
    name: "República Dominicana",
    demonym: "dominicanos",
    childTerm: "niños",
    currency: "DOP",
    currencySymbol: "RD$",
    priceUSD: 267,
    priceLocal: 15800,
    priceDisplay: "RD$ 15,800",
    reservationPrice: 1600,
    reservationPriceDisplay: "RD$ 1,600",
    whatsapp: "+56964754219",
    timezone: "America/Santo_Domingo",
    mainCity: "Santo Domingo",
    otherCities: ["Santiago de los Caballeros", "Punta Cana", "Puerto Plata"],
    locale: "es_DO",
    hreflang: "es-DO",
    tone: "Futuro tecnológico para el Caribe",
    keywords: ["cursos de ia para niños republica dominicana", "clases de programacion santo domingo"],
    longTailKeywords: ["campamento de verano tecnologico republica dominicana"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇩🇴",
    metaTitle: "Curso de IA para Niños en Rep. Dominicana | Online y Certificado | InnovaKids",
    metaDescription: "🇩🇴 Curso #1 de IA para niños en R.D. (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Santo Domingo, Santiago y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  hn: {
    code: "hn",
    name: "Honduras",
    demonym: "hondureños",
    childTerm: "niños",
    currency: "HNL",
    currencySymbol: "L",
    priceUSD: 267,
    priceLocal: 6600,
    priceDisplay: "L 6,600",
    reservationPrice: 660,
    reservationPriceDisplay: "L 660",
    whatsapp: "+56964754219",
    timezone: "America/Tegucigalpa",
    mainCity: "Tegucigalpa",
    otherCities: ["San Pedro Sula", "La Ceiba", "Choluteca"],
    locale: "es_HN",
    hreflang: "es-HN",
    tone: "Oportunidades globales desde Honduras",
    keywords: ["cursos de ia para niños honduras", "clases de computacion tegucigalpa"],
    longTailKeywords: ["donde estudiar programacion niños honduras"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇭🇳",
    metaTitle: "Curso de IA para Niños en Honduras | Online y Certificado | InnovaKids",
    metaDescription: "🇭🇳 Curso #1 de IA para niños en Honduras (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Tegucigalpa, San Pedro Sula y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  sv: {
    code: "sv",
    name: "El Salvador",
    demonym: "salvadoreños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/El_Salvador",
    mainCity: "San Salvador",
    otherCities: ["Santa Ana", "San Miguel", "Santa Tecla"],
    locale: "es_SV",
    hreflang: "es-SV",
    tone: "El futuro es tech en El Salvador",
    keywords: ["cursos de ia para niños el salvador", "clases de programacion san salvador"],
    longTailKeywords: ["academia de programacion para niños el salvador"],
    paymentMethods: ["Tarjeta", "PayPal", "Bitcoin (Chivo)"],
    flag: "🇸🇻",
    metaTitle: "Curso de IA para Niños en El Salvador | Online y Certificado | InnovaKids",
    metaDescription: "🇸🇻 Curso #1 de IA para niños en El Salvador (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en San Salvador, Santa Ana y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito, PayPal o Bitcoin. La reserva es de $27 USD."
  },
  gt: {
    code: "gt",
    name: "Guatemala",
    demonym: "guatemaltecos",
    childTerm: "patojos",
    currency: "GTQ",
    currencySymbol: "Q",
    priceUSD: 267,
    priceLocal: 2000,
    priceDisplay: "Q 2,000",
    reservationPrice: 200,
    reservationPriceDisplay: "Q 200",
    whatsapp: "+56964754219",
    timezone: "America/Guatemala",
    mainCity: "Ciudad de Guatemala",
    otherCities: ["Quetzaltenango", "Escuintla", "Antigua"],
    locale: "es_GT",
    hreflang: "es-GT",
    tone: "Desarrolla el talento chapín",
    keywords: ["cursos de ia para niños guatemala", "clases de programacion guatemala"],
    longTailKeywords: ["cursos de robotica para niños en guatemala"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇬🇹",
    metaTitle: "Curso de IA para Niños en Guatemala | Online y Certificado | InnovaKids",
    metaDescription: "🇬🇹 Curso #1 de IA para niños en Guatemala (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Ciudad de Guatemala, Xela y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  py: {
    code: "py",
    name: "Paraguay",
    demonym: "paraguayos",
    childTerm: "niños",
    currency: "PYG",
    currencySymbol: "₲",
    priceUSD: 267,
    priceLocal: 2000000,
    priceDisplay: "₲ 2.000.000",
    reservationPrice: 200000,
    reservationPriceDisplay: "₲ 200.000",
    whatsapp: "+56964754219",
    timezone: "America/Asuncion",
    mainCity: "Asunción",
    otherCities: ["Ciudad del Este", "Encarnación", "Luque"],
    locale: "es_PY",
    hreflang: "es-PY",
    tone: "Tecnología sin fronteras en Paraguay",
    keywords: ["cursos de ia para niños paraguay", "clases de programacion asuncion"],
    longTailKeywords: ["cursos de informatica para niños asuncion"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇵🇾",
    metaTitle: "Curso de IA para Niños en Paraguay | Online y Certificado | InnovaKids",
    metaDescription: "🇵🇾 Curso #1 de IA para niños en Paraguay (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Asunción, Ciudad del Este y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  bo: {
    code: "bo",
    name: "Bolivia",
    demonym: "bolivianos",
    childTerm: "niños",
    currency: "BOB",
    currencySymbol: "Bs",
    priceUSD: 267,
    priceLocal: 1850,
    priceDisplay: "Bs 1.850",
    reservationPrice: 185,
    reservationPriceDisplay: "Bs 185",
    whatsapp: "+56964754219",
    timezone: "America/La_Paz",
    mainCity: "La Paz",
    otherCities: ["Santa Cruz de la Sierra", "Cochabamba", "El Alto"],
    locale: "es_BO",
    hreflang: "es-BO",
    tone: "Impulsando el talento en Bolivia",
    keywords: ["cursos de ia para niños bolivia", "clases de programacion la paz"],
    longTailKeywords: ["robotica para niños santa cruz bolivia"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇧🇴",
    metaTitle: "Curso de IA para Niños en Bolivia | Online y Certificado | InnovaKids",
    metaDescription: "🇧🇴 Curso #1 de IA para niños en Bolivia (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en La Paz, Santa Cruz y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  ni: {
    code: "ni",
    name: "Nicaragua",
    demonym: "nicaragüenses",
    childTerm: "niños",
    currency: "NIO",
    currencySymbol: "C$",
    priceUSD: 267,
    priceLocal: 9800,
    priceDisplay: "C$ 9,800",
    reservationPrice: 980,
    reservationPriceDisplay: "C$ 980",
    whatsapp: "+56964754219",
    timezone: "America/Managua",
    mainCity: "Managua",
    otherCities: ["León", "Masaya", "Matagalpa"],
    locale: "es_NI",
    hreflang: "es-NI",
    tone: "Futuro digital en Nicaragua",
    keywords: ["cursos de ia para niños nicaragua", "clases de programacion managua"],
    longTailKeywords: ["cursos de computacion para niños en managua"],
    paymentMethods: ["Tarjeta", "PayPal"],
    flag: "🇳🇮",
    metaTitle: "Curso de IA para Niños en Nicaragua | Online y Certificado | InnovaKids",
    metaDescription: "🇳🇮 Curso #1 de IA para niños en Nicaragua (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Managua, León y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito o PayPal. La reserva es de $27 USD."
  },
  pr: {
    code: "pr",
    name: "Puerto Rico",
    demonym: "puertorriqueños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Puerto_Rico",
    mainCity: "San Juan",
    otherCities: ["Bayamón", "Carolina", "Ponce"],
    locale: "es_PR",
    hreflang: "es-PR",
    tone: "Innovación caribeña y global",
    keywords: ["cursos de ia para niños puerto rico", "clases de coding puerto rico"],
    longTailKeywords: ["campamentos de verano puerto rico tecnologia"],
    paymentMethods: ["Tarjeta", "PayPal", "ATH Móvil (consultar)"],
    flag: "🇵🇷",
    metaTitle: "Curso de IA para Niños en Puerto Rico | Online y Certificado | InnovaKids",
    metaDescription: "🇵🇷 Curso #1 de IA para niños en Puerto Rico (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en San Juan, Bayamón y toda la isla ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito, PayPal o consultar por ATH Móvil. La reserva es de $27 USD."
  },
  gq: {
    code: "gq",
    name: "Guinea Ecuatorial",
    demonym: "ecuatoguineanos",
    childTerm: "niños",
    currency: "XAF",
    currencySymbol: "FCFA",
    priceUSD: 267,
    priceLocal: 160000,
    priceDisplay: "160.000 FCFA",
    reservationPrice: 16000,
    reservationPriceDisplay: "16.000 FCFA",
    whatsapp: "+56964754219",
    timezone: "Africa/Malabo",
    mainCity: "Malabo",
    otherCities: ["Bata", "Ebebiyín"],
    locale: "es_GQ",
    hreflang: "es-GQ",
    tone: "Conectando África con el futuro",
    keywords: ["cursos de ia para niños guinea ecuatorial", "clases de informatica malabo"],
    longTailKeywords: ["formacion tecnologica en guinea ecuatorial"],
    paymentMethods: ["Tarjeta", "PayPal", "Transferencia"],
    flag: "🇬🇶",
    metaTitle: "Curso de IA para Niños en Guinea Ecuatorial | Online y Certificado | InnovaKids",
    metaDescription: "🇬🇶 Curso #1 de IA para niños en Guinea Ecuatorial (8-17 años). Aprende a programar, crear apps y más. Clase de Prueba GRATIS. ¡Reserva tu cupo hoy!",
    heroSubtext: "Familias en Malabo, Bata y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Puedes pagar con tarjeta de crédito internacional o PayPal. La reserva es de $27 USD."
  }
}

export const getCountryConfig = (code: CountryCode): CountryConfig => {
  return countriesConfig[code]
}

export const getAllCountryCodes = (): CountryCode[] => {
  return Object.keys(countriesConfig) as CountryCode[]
}
