export type CountryCode = "mx" | "co" | "ar" | "es" | "cl" | "pe" | "ec" | "uy" | "cr" | "ve" | "us" | "pa" | "do" | "hn" | "sv" | "gt" | "py" | "bo" | "ni" | "pr" | "gq"

export interface CountryConfig {
  code: CountryCode
  name: string
  demonym: string
  childTerm: string // "niños" vs "chicos" vs "chavales"
  currency: string
  currencySymbol: string
  priceUSD: number
  priceLocal: number
  priceDisplay: string
  reservationPrice: number
  reservationPriceDisplay: string
  whatsapp: string
  timezone: string
  mainCity: string
  otherCities: string[]
  locale: string
  hreflang: string
  tone: string
  keywords: string[]
  longTailKeywords: string[]
  paymentMethods: string[]
  flag: string
  metaTitle: string
  metaDescription: string
  heroSubtext: string
  faqPaymentAnswer: string
}

export const countriesConfig: Record<CountryCode, CountryConfig> = {
  cl: {
    code: "cl",
    name: "Chile",
    demonym: "chilenos",
    childTerm: "niños",
    currency: "CLP",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 250000,
    priceDisplay: "$267 USD (aprox. $250.000 CLP)",
    reservationPrice: 25000,
    reservationPriceDisplay: "$27 USD (aprox. $25.000 CLP)",
    whatsapp: "+56964754219",
    timezone: "America/Santiago",
    mainCity: "Santiago",
    otherCities: ["Viña del Mar", "Valparaíso", "Concepción", "La Serena"],
    locale: "es_CL",
    hreflang: "es-CL",
    tone: "Prepáralos para el futuro digital",
    keywords: [
      "curso de ia para niños chile",
      "cursos ia para adolescentes chile",
      "clases inteligencia artificial niños santiago",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños chilenos",
      "donde estudiar programación con ia niños en chile",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇨🇱",
    metaTitle: "Curso de IA para Niños en Chile — Tu Hijo Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Chile. Clases en vivo, máx 5 alumnos (8-17 años). 527 graduados en 9 países. 1ª clase gratis.",
    heroSubtext: "Familias en Santiago, Viña del Mar, Concepción y todo Chile ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. $25.000 CLP). Solo pagas el resto después de las 2 primeras clases."
  },
  mx: {
    code: "mx",
    name: "México",
    demonym: "mexicanos",
    childTerm: "niños",
    currency: "MXN",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 5400,
    priceDisplay: "$267 USD (aprox. $5,400 MXN)",
    reservationPrice: 540,
    reservationPriceDisplay: "$27 USD (aprox. $540 MXN)",
    whatsapp: "+56964754219",
    timezone: "America/Mexico_City",
    mainCity: "CDMX",
    otherCities: ["Guadalajara", "Monterrey", "Puebla", "Tijuana"],
    locale: "es_MX",
    hreflang: "es-MX",
    tone: "Dale una ventaja competitiva a tu hijo",
    keywords: [
      "curso de ia para niños mexico",
      "cursos ia para adolescentes mexico",
      "clases de IA para niños cdmx",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños mexicanos",
      "donde aprenden IA mis hijos en méxico",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇲🇽",
    metaTitle: "Curso de IA para Niños en México — Tu Hijo Crea Apps con IA",
    metaDescription: "Niños y adolescentes en México (8-17 años) crean videojuegos, apps y arte con Inteligencia Artificial. Clases en vivo, grupos de máx 5. Prueba gratis.",
    heroSubtext: "Familias en Ciudad de México, Guadalajara, Monterrey y todo México ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. $540 MXN). Solo pagas el resto después de las 2 primeras clases."
  },
  co: {
    code: "co",
    name: "Colombia",
    demonym: "colombianos",
    childTerm: "niños",
    currency: "COP",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 1120000,
    priceDisplay: "$267 USD (aprox. $1.120.000 COP)",
    reservationPrice: 113000,
    reservationPriceDisplay: "$27 USD (aprox. $113.000 COP)",
    whatsapp: "+56964754219",
    timezone: "America/Bogota",
    mainCity: "Bogotá",
    otherCities: ["Medellín", "Cali", "Barranquilla", "Cartagena"],
    locale: "es_CO",
    hreflang: "es-CO",
    tone: "Impulsa su creatividad y espíritu innovador",
    keywords: [
      "curso de ia para niños colombia",
      "cursos ia para adolescentes colombia",
      "clases de IA para niños bogota",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "aprendizaje de inteligencia artificial para niños",
      "clases de inteligencia artificial para adolescentes"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños colombianos",
      "donde estudiar ia niños en colombia",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇨🇴",
    metaTitle: "Curso de IA para Niños en Colombia — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Colombia. Clases en vivo, máx 5 alumnos (8-17 años). 527 graduados en 9 países. 1ª clase gratis.",
    heroSubtext: "Familias en Bogotá, Medellín, Cali, Barranquilla y toda Colombia ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. $113.000 COP). Solo pagas el resto después de las 2 primeras clases."
  },
  ar: {
    code: "ar",
    name: "Argentina",
    demonym: "argentinos",
    childTerm: "chicos",
    currency: "ARS",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 285000,
    priceDisplay: "$267 USD (aprox. $285.000 ARS)",
    reservationPrice: 29000,
    reservationPriceDisplay: "$27 USD (aprox. $29.000 ARS)",
    whatsapp: "+56964754219",
    timezone: "America/Argentina/Buenos_Aires",
    mainCity: "Buenos Aires",
    otherCities: ["Córdoba", "Rosario", "Mendoza", "La Plata"],
    locale: "es_AR",
    hreflang: "es-AR",
    tone: "Potencia su pensamiento crítico creando tecnología",
    keywords: [
      "curso de ia para chicos argentina",
      "cursos ia para adolescentes argentina",
      "clases ia para chicos buenos aires",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "inteligencia artificial para adolescentes",
      "aprendizaje de inteligencia artificial para niños"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para chicos argentinos",
      "donde aprenden ia los chicos en argentina",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇦🇷",
    metaTitle: "Curso de IA para Chicos en Argentina — Crean Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Argentina. Clases en vivo, máx 5 alumnos (8-17 años). Paga con Mercado Pago. 1ª clase gratis.",
    heroSubtext: "Familias en Buenos Aires, Córdoba, Rosario y toda Argentina ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito o débito internacional. El cobro seguro en plataforma procesa sin fricción. La reserva es de $27 USD. Solo pagas el resto después de las 2 primeras clases."
  },
  pe: {
    code: "pe",
    name: "Perú",
    demonym: "peruanos",
    childTerm: "niños",
    currency: "PEN",
    currencySymbol: "S/",
    priceUSD: 267,
    priceLocal: 1000,
    priceDisplay: "$267 USD (aprox. S/ 1.000 PEN)",
    reservationPrice: 100,
    reservationPriceDisplay: "$27 USD (aprox. S/ 100 PEN)",
    whatsapp: "+56964754219",
    timezone: "America/Lima",
    mainCity: "Lima",
    otherCities: ["Arequipa", "Trujillo", "Cusco", "Piura"],
    locale: "es_PE",
    hreflang: "es-PE",
    tone: "Educación tecnológica de clase mundial",
    keywords: [
      "curso de ia para niños peru",
      "cursos ia para adolescentes peru",
      "clases de IA para niños lima",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "aprendizaje de inteligencia artificial para niños",
      "clases de inteligencia artificial para adolescentes"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños peruanos",
      "donde estudiar ia niños en peru",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇵🇪",
    metaTitle: "Curso de IA para Niños en Perú — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Perú. Clases en vivo, máx 5 alumnos (8-17 años). Paga con Yape o tarjeta. 1ª clase gratis.",
    heroSubtext: "Familias en Lima, Arequipa, Trujillo y todo Perú ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. S/ 100). Solo pagas el resto después de las 2 primeras clases."
  },
  es: {
    code: "es",
    name: "España",
    demonym: "españoles",
    childTerm: "niños",
    currency: "EUR",
    currencySymbol: "€",
    priceUSD: 267,
    priceLocal: 245,
    priceDisplay: "$267 USD (aprox. 245€)",
    reservationPrice: 25,
    reservationPriceDisplay: "$27 USD (aprox. 25€)",
    whatsapp: "+56964754219",
    timezone: "Europe/Madrid",
    mainCity: "Madrid",
    otherCities: ["Barcelona", "Valencia", "Sevilla", "Bilbao"],
    locale: "es_ES",
    hreflang: "es-ES",
    tone: "Formación tecnológica de alta calidad",
    keywords: [
      "curso de ia para niños españa",
      "cursos ia para adolescentes madrid",
      "clases inteligencia artificial niños barcelona",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "extraescolar ia niños",
      "curso ia adolescentes madrid"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños españoles",
      "donde estudiar programación con ia niños en españa",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇪🇸",
    metaTitle: "Extraescolar de IA para Niños en España — Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en España. Extraescolar online en vivo, máx 5 alumnos (8-17 años). Paga con Bizum. 1ª clase gratis.",
    heroSubtext: "Familias en Madrid, Barcelona, Valencia, Sevilla y toda España ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. 25€). Tu hijo prueba las 2 primeras clases y solo si te convence pagas el resto."
  },
  ec: {
    code: "ec",
    name: "Ecuador",
    demonym: "ecuatorianos",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Guayaquil",
    mainCity: "Quito",
    otherCities: ["Guayaquil", "Cuenca", "Ambato"],
    locale: "es_EC",
    hreflang: "es-EC",
    tone: "Innovación y tecnología al alcance de tus hijos",
    keywords: [
      "curso de ia para niños ecuador",
      "cursos ia para adolescentes quito",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "curso vacacional de inteligencia artificial",
      "cursos de inteligencia artificial guayaquil",
      "cursos de ia en ecuador"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en guayaquil",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇪🇨",
    metaTitle: "Curso de IA para Niños en Ecuador — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Ecuador. Clases en vivo, máx 5 alumnos (8-17 años). Pago directo en USD. 1ª clase gratis.",
    heroSubtext: "Familias en Quito, Guayaquil, Cuenca y todo Ecuador ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de solo $27 USD. Después de las 2 primeras clases pagas el resto."
  },
  uy: {
    code: "uy",
    name: "Uruguay",
    demonym: "uruguayos",
    childTerm: "chiquilines",
    currency: "UYU",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 11500,
    priceDisplay: "$267 USD (aprox. $11.500 UYU)",
    reservationPrice: 1160,
    reservationPriceDisplay: "$27 USD (aprox. $1.160 UYU)",
    whatsapp: "+56964754219",
    timezone: "America/Montevideo",
    mainCity: "Montevideo",
    otherCities: ["Punta del Este", "Salto", "Ciudad de la Costa"],
    locale: "es_UY",
    hreflang: "es-UY",
    tone: "Educación de calidad para el futuro",
    keywords: [
      "curso de ia para niños uruguay",
      "cursos ia para adolescentes montevideo",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de programación con ia para niños en uruguay",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇺🇾",
    metaTitle: "Curso de IA para Niños en Uruguay — Tu Hijo Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Uruguay. Clases en vivo, máx 5 alumnos (8-17 años). Paga con Mercado Pago. 1ª clase gratis.",
    heroSubtext: "Familias en Montevideo, Punta del Este y todo Uruguay ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox $1.160 UYU). Después de las 2 primeras clases pagas el resto."
  },
  cr: {
    code: "cr",
    name: "Costa Rica",
    demonym: "ticos",
    childTerm: "niños",
    currency: "CRC",
    currencySymbol: "₡",
    priceUSD: 267,
    priceLocal: 137000,
    priceDisplay: "$267 USD (aprox. ₡137.000 CRC)",
    reservationPrice: 14000,
    reservationPriceDisplay: "$27 USD (aprox. ₡14.000 CRC)",
    whatsapp: "+56964754219",
    timezone: "America/Costa_Rica",
    mainCity: "San José",
    otherCities: ["Heredia", "Alajuela", "Cartago"],
    locale: "es_CR",
    hreflang: "es-CR",
    tone: "Líderes en educación tecnológica",
    keywords: [
      "curso de ia para niños costa rica",
      "cursos ia para adolescentes san jose",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en costa rica",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇨🇷",
    metaTitle: "Curso de IA para Niños en Costa Rica — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Costa Rica. Clases en vivo, máx 5 alumnos (8-17 años). Paga con SINPE. 1ª clase gratis.",
    heroSubtext: "Familias en San José, Heredia, Alajuela y toda Costa Rica ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox ₡14.000 CRC)."
  },
  ve: {
    code: "ve",
    name: "Venezuela",
    demonym: "venezolanos",
    childTerm: "chamos",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Caracas",
    mainCity: "Caracas",
    otherCities: ["Maracaibo", "Valencia", "Barquisimeto"],
    locale: "es_VE",
    hreflang: "es-VE",
    tone: "Tecnología global y oportunidades de futuro",
    keywords: [
      "curso de ia para niños venezuela",
      "cursos ia para adolescentes caracas",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en venezuela",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇻🇪",
    metaTitle: "Curso de IA para Niños en Venezuela — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Venezuela. Clases en vivo, máx 5 alumnos (8-17 años). Pago en USD. 1ª clase gratis.",
    heroSubtext: "Familias en Caracas, Maracaibo, Valencia y toda Venezuela ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito o débito internacional. Procesamos el cobro de forma segura y sin fricción. La reserva es de $27 USD."
  },
  us: {
    code: "us",
    name: "Estados Unidos",
    demonym: "latinos",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/New_York",
    mainCity: "Miami",
    otherCities: ["Los Angeles", "Houston", "New York", "Chicago"],
    locale: "es_US",
    hreflang: "es-US",
    tone: "Vibe Coding: La ventaja bilingüe y tecnológica",
    keywords: [
      "curso de ia para niños latinos usa",
      "cursos ia para adolescentes español miami",
      "cursos online para niños hispanos",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "clases de ia para niños en español usa",
      "cursos de ia para niños en miami",
      "cursos de inteligencia artificial en miami"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños hispanos en estados unidos",
      "cursos para niños de 10 a 12 años en usa",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños hispanos",
      "escuela online de inteligencia artificial en español",
      "aprender inteligencia artificial online en español",
      "curso de tecnología para niños latinos en usa",
      "vibe coding para niños",
      "ia kids usa",
      "cursos de ia para niños en california",
      "cursos de ia para niños en texas"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito de USA", "PayPal"],
    flag: "🇺🇸",
    metaTitle: "Curso de IA para Niños y Adolescentes en USA · Clase Gratis",
    metaDescription: "Niños latinos (8-17) en Miami, LA, Houston y toda USA crean apps y videojuegos con IA. Clases en vivo 100% en español, grupos de 5. ★4.9 de 527 familias. 1ª clase gratis.",
    heroSubtext: "Familias latinas en Miami, California, Texas y todo USA ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito de USA o PayPal. La reserva es de $27 USD."
  },
  pa: {
    code: "pa",
    name: "Panamá",
    demonym: "panameños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Panama",
    mainCity: "Ciudad de Panamá",
    otherCities: ["Colón", "David", "Santiago"],
    locale: "es_PA",
    hreflang: "es-PA",
    tone: "Innovación desde el Hub de las Américas",
    keywords: [
      "curso de ia para niños panama",
      "cursos ia para adolescentes panama",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial",
      "curso de ia en panama",
      "escuela de ia panama",
      "escuela de tecnologia para niños"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en panama",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇵🇦",
    metaTitle: "Curso de IA para Niños en Panamá — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Panamá. Clases en vivo, máx 5 alumnos (8-17 años). Pago en USD. 1ª clase gratis.",
    heroSubtext: "Familias en Ciudad de Panamá, Colón y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD."
  },
  do: {
    code: "do",
    name: "República Dominicana",
    demonym: "dominicanos",
    childTerm: "niños",
    currency: "DOP",
    currencySymbol: "RD$",
    priceUSD: 267,
    priceLocal: 15800,
    priceDisplay: "$267 USD (aprox. RD$ 15,800)",
    reservationPrice: 1600,
    reservationPriceDisplay: "$27 USD (aprox. RD$ 1,600)",
    whatsapp: "+56964754219",
    timezone: "America/Santo_Domingo",
    mainCity: "Santo Domingo",
    otherCities: ["Santiago de los Caballeros", "Punta Cana", "Puerto Plata"],
    locale: "es_DO",
    hreflang: "es-DO",
    tone: "Futuro tecnológico para el Caribe",
    keywords: [
      "curso de ia para niños republica dominicana",
      "cursos ia para adolescentes santo domingo",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en republica dominicana",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇩🇴",
    metaTitle: "Curso de IA para Niños en R. Dominicana — Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Rep. Dominicana. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Santo Domingo, Santiago y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD."
  },
  hn: {
    code: "hn",
    name: "Honduras",
    demonym: "hondureños",
    childTerm: "niños",
    currency: "HNL",
    currencySymbol: "L",
    priceUSD: 267,
    priceLocal: 6600,
    priceDisplay: "$267 USD (aprox. L 6,600)",
    reservationPrice: 660,
    reservationPriceDisplay: "$27 USD (aprox. L 660)",
    whatsapp: "+56964754219",
    timezone: "America/Tegucigalpa",
    mainCity: "Tegucigalpa",
    otherCities: ["San Pedro Sula", "La Ceiba", "Choluteca"],
    locale: "es_HN",
    hreflang: "es-HN",
    tone: "Oportunidades globales desde Honduras",
    keywords: [
      "curso de ia para niños honduras",
      "cursos ia para adolescentes honduras",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en honduras",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇭🇳",
    metaTitle: "Curso de IA para Niños en Honduras — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Honduras. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Tegucigalpa, San Pedro Sula y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. L 660)."
  },
  sv: {
    code: "sv",
    name: "El Salvador",
    demonym: "salvadoreños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/El_Salvador",
    mainCity: "San Salvador",
    otherCities: ["Santa Ana", "San Miguel", "Santa Tecla"],
    locale: "es_SV",
    hreflang: "es-SV",
    tone: "El futuro es tech en El Salvador",
    keywords: [
      "curso de ia para niños el salvador",
      "cursos ia para adolescentes san salvador",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en el salvador",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇸🇻",
    metaTitle: "Curso de IA para Niños en El Salvador — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en El Salvador. Clases en vivo, máx 5 alumnos (8-17 años). Pago en USD. 1ª clase gratis.",
    heroSubtext: "Familias en San Salvador, Santa Ana y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD."
  },
  gt: {
    code: "gt",
    name: "Guatemala",
    demonym: "guatemaltecos",
    childTerm: "patojos",
    currency: "GTQ",
    currencySymbol: "Q",
    priceUSD: 267,
    priceLocal: 2000,
    priceDisplay: "$267 USD (aprox. Q 2,000)",
    reservationPrice: 200,
    reservationPriceDisplay: "$27 USD (aprox. Q 200)",
    whatsapp: "+56964754219",
    timezone: "America/Guatemala",
    mainCity: "Ciudad de Guatemala",
    otherCities: ["Quetzaltenango", "Escuintla", "Antigua"],
    locale: "es_GT",
    hreflang: "es-GT",
    tone: "Desarrolla el talento chapín",
    keywords: [
      "curso de ia para niños guatemala",
      "cursos ia para adolescentes guatemala",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en guatemala",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇬🇹",
    metaTitle: "Curso de IA para Niños en Guatemala — Crean Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Guatemala. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Ciudad de Guatemala, Xela y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. Q 200)."
  },
  py: {
    code: "py",
    name: "Paraguay",
    demonym: "paraguayos",
    childTerm: "niños",
    currency: "PYG",
    currencySymbol: "₲",
    priceUSD: 267,
    priceLocal: 2000000,
    priceDisplay: "$267 USD (aprox. ₲ 2.000.000)",
    reservationPrice: 200000,
    reservationPriceDisplay: "$27 USD (aprox. ₲ 200.000)",
    whatsapp: "+56964754219",
    timezone: "America/Asuncion",
    mainCity: "Asunción",
    otherCities: ["Ciudad del Este", "Encarnación", "Luque"],
    locale: "es_PY",
    hreflang: "es-PY",
    tone: "Tecnología sin fronteras en Paraguay",
    keywords: [
      "curso de ia para niños paraguay",
      "cursos ia para adolescentes paraguay",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en paraguay",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇵🇾",
    metaTitle: "Curso de IA para Niños en Paraguay — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Paraguay. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Asunción, Ciudad del Este y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. ₲ 200.000)."
  },
  bo: {
    code: "bo",
    name: "Bolivia",
    demonym: "bolivianos",
    childTerm: "niños",
    currency: "BOB",
    currencySymbol: "Bs",
    priceUSD: 267,
    priceLocal: 1850,
    priceDisplay: "$267 USD (aprox. Bs 1.850)",
    reservationPrice: 185,
    reservationPriceDisplay: "$27 USD (aprox. Bs 185)",
    whatsapp: "+56964754219",
    timezone: "America/La_Paz",
    mainCity: "La Paz",
    otherCities: ["Santa Cruz de la Sierra", "Cochabamba", "El Alto"],
    locale: "es_BO",
    hreflang: "es-BO",
    tone: "Impulsando el talento en Bolivia",
    keywords: [
      "curso de ia para niños bolivia",
      "cursos ia para adolescentes bolivia",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en bolivia",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇧🇴",
    metaTitle: "Curso de IA para Niños en Bolivia — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Bolivia. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en La Paz, Santa Cruz y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. Bs 185)."
  },
  ni: {
    code: "ni",
    name: "Nicaragua",
    demonym: "nicaragüenses",
    childTerm: "niños",
    currency: "NIO",
    currencySymbol: "C$",
    priceUSD: 267,
    priceLocal: 9800,
    priceDisplay: "$267 USD (aprox. C$ 9,800)",
    reservationPrice: 980,
    reservationPriceDisplay: "$27 USD (aprox. C$ 980)",
    whatsapp: "+56964754219",
    timezone: "America/Managua",
    mainCity: "Managua",
    otherCities: ["León", "Masaya", "Matagalpa"],
    locale: "es_NI",
    hreflang: "es-NI",
    tone: "Futuro digital en Nicaragua",
    keywords: [
      "curso de ia para niños nicaragua",
      "cursos ia para adolescentes nicaragua",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en nicaragua",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇳🇮",
    metaTitle: "Curso de IA para Niños en Nicaragua — Crea Apps y Videojuegos",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Nicaragua. Clases en vivo, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Managua, León y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD (aprox. C$ 980)."
  },
  pr: {
    code: "pr",
    name: "Puerto Rico",
    demonym: "puertorriqueños",
    childTerm: "niños",
    currency: "USD",
    currencySymbol: "$",
    priceUSD: 267,
    priceLocal: 267,
    priceDisplay: "$267 USD",
    reservationPrice: 27,
    reservationPriceDisplay: "$27 USD",
    whatsapp: "+56964754219",
    timezone: "America/Puerto_Rico",
    mainCity: "San Juan",
    otherCities: ["Bayamón", "Carolina", "Ponce"],
    locale: "es_PR",
    hreflang: "es-PR",
    tone: "Innovación caribeña y global",
    keywords: [
      "curso de ia para niños puerto rico",
      "cursos ia para adolescentes pr",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en puerto rico",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇵🇷",
    metaTitle: "Curso de IA para Niños en Puerto Rico — Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Puerto Rico. Clases en vivo en español, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en San Juan, Bayamón y toda la isla ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito, débito o PayPal. La reserva es de $27 USD."
  },
  gq: {
    code: "gq",
    name: "Guinea Ecuatorial",
    demonym: "ecuatoguineanos",
    childTerm: "niños",
    currency: "XAF",
    currencySymbol: "FCFA",
    priceUSD: 267,
    priceLocal: 160000,
    priceDisplay: "$267 USD (aprox. 160.000 FCFA)",
    reservationPrice: 16000,
    reservationPriceDisplay: "$27 USD (aprox. 16.000 FCFA)",
    whatsapp: "+56964754219",
    timezone: "Africa/Malabo",
    mainCity: "Malabo",
    otherCities: ["Bata", "Ebebiyín"],
    locale: "es_GQ",
    hreflang: "es-GQ",
    tone: "Conectando África con el futuro",
    keywords: [
      "curso de ia para niños guinea ecuatorial",
      "cursos ia para adolescentes malabo",
      "cursos online para niños",
      "curso de inteligencia artificial para adolescentes",
      "extraescolar de inteligencia artificial"
    ],
    longTailKeywords: [
      "mejor curso online de inteligencia artificial para niños en guinea ecuatorial",
      "cursos para niños de 10 a 12 años",
      "clases online de ia para adolescentes de 14 a 17 años",
      "taller extraescolar de tecnología para niños",
      "escuela online de inteligencia artificial",
      "aprender inteligencia artificial online",
      "curso de tecnología para niños",
      "vibe coding para niños",
      "ia kids"
    ],
    paymentMethods: ["Tarjeta de crédito", "Tarjeta de débito", "PayPal"],
    flag: "🇬🇶",
    metaTitle: "Curso de IA para Niños en Guinea Ecuatorial — Crea Apps con IA",
    metaDescription: "Tu hijo crea apps, videojuegos y arte con IA en Guinea Ecuatorial. Clases en vivo en español, máx 5 alumnos (8-17 años). 1ª clase gratis.",
    heroSubtext: "Familias en Malabo, Bata y todo el país ya aprenden con InnovaKids.",
    faqPaymentAnswer: "Proceso global y seguro: paga en 1 clic con cualquier tarjeta de crédito internacional, débito o PayPal. La reserva es de $27 USD."
  }
}

export const getCountryConfig = (code: CountryCode): CountryConfig => {
  return countriesConfig[code]
}

export const getAllCountryCodes = (): CountryCode[] => {
  return Object.keys(countriesConfig) as CountryCode[]
}
